CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE price (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES product (id),
    "value"     DECIMAL(12, 2) NOT NULL,
    init_date   DATE NOT NULL,
    end_date    DATE
);

CREATE INDEX idx_price_product_init_end ON price (product_id, init_date, end_date);
